import type { HoldingsResponse, ImportedHolding } from "./types";

export const DEMO_HOLDINGS: ImportedHolding[] = [
  {
    account_name: "TFSA",
    account_type: "TFSA",
    account_classification: "Tax-Free Savings Account",
    account_number: "DEMO-001",
    symbol: "XEQT",
    exchange: "TSX",
    mic: "XTSE",
    name: "iShares Core Equity ETF Portfolio",
    security_type: "ETF",
    quantity: 120,
    position_direction: "Long",
    market_price: 32.85,
    market_price_currency: "CAD",
    book_value_cad: 3600,
    book_value_currency_cad: "CAD",
    book_value_market: 3600,
    book_value_currency_market: "CAD",
    market_value: 3942,
    market_value_currency: "CAD",
    market_unrealized_returns: 342,
    market_unrealized_returns_currency: "CAD",
  },
  {
    account_name: "RRSP",
    account_type: "RRSP",
    account_classification: "Registered Retirement Savings Plan",
    account_number: "DEMO-002",
    symbol: "AAPL",
    exchange: "NASDAQ",
    mic: "XNAS",
    name: "Apple Inc.",
    security_type: "Common Stock",
    quantity: 25,
    position_direction: "Long",
    market_price: 187.5,
    market_price_currency: "USD",
    book_value_cad: 5200,
    book_value_currency_cad: "CAD",
    book_value_market: 3800,
    book_value_currency_market: "USD",
    market_value: 4687.5,
    market_value_currency: "USD",
    market_unrealized_returns: 887.5,
    market_unrealized_returns_currency: "USD",
  },
  {
    account_name: "RRSP",
    account_type: "RRSP",
    account_classification: "Registered Retirement Savings Plan",
    account_number: "DEMO-002",
    symbol: "MSFT",
    exchange: "NASDAQ",
    mic: "XNAS",
    name: "Microsoft Corporation",
    security_type: "Common Stock",
    quantity: 12,
    position_direction: "Long",
    market_price: 415,
    market_price_currency: "USD",
    book_value_cad: 5800,
    book_value_currency_cad: "CAD",
    book_value_market: 4200,
    book_value_currency_market: "USD",
    market_value: 4980,
    market_value_currency: "USD",
    market_unrealized_returns: 780,
    market_unrealized_returns_currency: "USD",
  },
  {
    account_name: "Margin",
    account_type: "Margin",
    account_classification: "Margin Account",
    account_number: "DEMO-003",
    symbol: "AMD",
    exchange: "NASDAQ",
    mic: "XNAS",
    name: "Advanced Micro Devices Inc.",
    security_type: "Common Stock",
    quantity: 40,
    position_direction: "Long",
    market_price: 125,
    market_price_currency: "USD",
    book_value_cad: 5100,
    book_value_currency_cad: "CAD",
    book_value_market: 3700,
    book_value_currency_market: "USD",
    market_value: 5000,
    market_value_currency: "USD",
    market_unrealized_returns: 1300,
    market_unrealized_returns_currency: "USD",
  },
  {
    account_name: "TFSA",
    account_type: "TFSA",
    account_classification: "Tax-Free Savings Account",
    account_number: "DEMO-001",
    symbol: "TD",
    exchange: "TSX",
    mic: "XTSE",
    name: "Toronto-Dominion Bank",
    security_type: "Common Stock",
    quantity: 50,
    position_direction: "Long",
    market_price: 78.4,
    market_price_currency: "CAD",
    book_value_cad: 3600,
    book_value_currency_cad: "CAD",
    book_value_market: 3600,
    book_value_currency_market: "CAD",
    market_value: 3920,
    market_value_currency: "CAD",
    market_unrealized_returns: 320,
    market_unrealized_returns_currency: "CAD",
  },
  {
    account_name: "Margin",
    account_type: "Margin",
    account_classification: "Margin Account",
    account_number: "DEMO-003",
    symbol: "CEG",
    exchange: "NASDAQ",
    mic: "XNAS",
    name: "Constellation Energy Corporation",
    security_type: "Common Stock",
    quantity: 8,
    position_direction: "Long",
    market_price: 265,
    market_price_currency: "USD",
    book_value_cad: 2400,
    book_value_currency_cad: "CAD",
    book_value_market: 1750,
    book_value_currency_market: "USD",
    market_value: 2120,
    market_value_currency: "USD",
    market_unrealized_returns: 370,
    market_unrealized_returns_currency: "USD",
  },
  {
    account_name: "RRSP",
    account_type: "RRSP",
    account_classification: "Registered Retirement Savings Plan",
    account_number: "DEMO-002",
    symbol: "GOOG",
    exchange: "NASDAQ",
    mic: "XNAS",
    name: "Alphabet Inc.",
    security_type: "Common Stock",
    quantity: 20,
    position_direction: "Long",
    market_price: 168,
    market_price_currency: "USD",
    book_value_cad: 3100,
    book_value_currency_cad: "CAD",
    book_value_market: 2250,
    book_value_currency_market: "USD",
    market_value: 3360,
    market_value_currency: "USD",
    market_unrealized_returns: 1110,
    market_unrealized_returns_currency: "USD",
  },
];

export const DEMO_HOLDINGS_RESPONSE: HoldingsResponse = {
  source_file_name: "demo-portfolio.csv",
  as_of: "2026-04-25",
  imported_at: "2026-04-25T00:00:00Z",
  holdings: DEMO_HOLDINGS,
};
