const TICKER_DOMAINS: Record<string, string> = {
  // ── Tech / semiconductors ─────────────────────────────────────────────────
  AAPL: "apple.com",
  MSFT: "microsoft.com",
  GOOG: "google.com",
  GOOGL: "google.com",
  META: "meta.com",
  AMZN: "amazon.com",
  NVDA: "nvidia.com",
  TSLA: "tesla.com",
  AMD: "amd.com",
  INTC: "intel.com",
  QCOM: "qualcomm.com",
  AVGO: "broadcom.com",
  MU: "micron.com",
  TXN: "ti.com",
  AMAT: "appliedmaterials.com",
  LRCX: "lamresearch.com",
  KLAC: "kla.com",
  ASML: "asml.com",
  CRM: "salesforce.com",
  ORCL: "oracle.com",
  ADBE: "adobe.com",
  NOW: "servicenow.com",
  INTU: "intuit.com",
  PANW: "paloaltonetworks.com",
  SNOW: "snowflake.com",
  PLTR: "palantir.com",
  NET: "cloudflare.com",
  DDOG: "datadoghq.com",
  ZS: "zscaler.com",
  IBM: "ibm.com",
  DELL: "dell.com",
  HPQ: "hp.com",
  // ── Finance ───────────────────────────────────────────────────────────────
  JPM: "jpmorganchase.com",
  BAC: "bankofamerica.com",
  WFC: "wellsfargo.com",
  GS: "goldmansachs.com",
  MS: "morganstanley.com",
  C: "citigroup.com",
  V: "visa.com",
  MA: "mastercard.com",
  AXP: "americanexpress.com",
  BRK: "berkshirehathaway.com",
  // ── Energy / utilities ────────────────────────────────────────────────────
  ETN: "eaton.com",
  GEV: "gevernova.com",
  CEG: "constellationenergy.com",
  VST: "vistraenergy.com",
  NEE: "nexteraenergy.com",
  XOM: "exxonmobil.com",
  CVX: "chevron.com",
  COP: "conocophillips.com",
  SLB: "slb.com",
  // ── Healthcare ────────────────────────────────────────────────────────────
  JNJ: "jnj.com",
  UNH: "uhc.com",
  PFE: "pfizer.com",
  ABBV: "abbvie.com",
  LLY: "lilly.com",
  MRK: "merck.com",
  AMGN: "amgen.com",
  BMY: "bms.com",
  ABT: "abbott.com",
  MDT: "medtronic.com",
  // ── Consumer ─────────────────────────────────────────────────────────────
  COST: "costco.com",
  WMT: "walmart.com",
  HD: "homedepot.com",
  MCD: "mcdonalds.com",
  SBUX: "starbucks.com",
  NKE: "nike.com",
  DIS: "disney.com",
  NFLX: "netflix.com",
  // ── Canadian ─────────────────────────────────────────────────────────────
  RY: "rbc.com",
  TD: "td.com",
  BNS: "scotiabank.com",
  BMO: "bmo.com",
  CM: "cibc.com",
  CNR: "cn.ca",
  CP: "cpr.ca",
  SU: "suncor.com",
  ENB: "enbridge.com",
  TRP: "tcenergy.com",
  // ── ETFs (index providers) ────────────────────────────────────────────────
  XEQT: "ishares.com",
  XGRO: "ishares.com",
  XBAL: "ishares.com",
  VFV: "vanguard.ca",
  VOO: "vanguard.com",
  VTI: "vanguard.com",
  QQQ: "invesco.com",
  SPY: "ssga.com",
  IVV: "ishares.com",
  GLD: "ssga.com",
};

export function getTickerLogoUrl(symbol: string): string | null {
  const domain = TICKER_DOMAINS[symbol.toUpperCase()];
  if (!domain) return null;
  return `https://logo.clearbit.com/${domain}?size=64`;
}
